import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Invoice, Profile } from '@/lib/types';
import { formatDate, formatLKR } from '@/lib/utils';

export function generateMonthlyInvoiceReportPdf(
  invoices: Invoice[],
  year: number,
  month: number,
  profile?: Profile | null,
  monthlyPaymentsCollected: number = 0
): void {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = 210;
  const pageHeight = 297;
  const marginX = 14;
  const contentWidth = pageWidth - marginX * 2; // 182mm

  const monthNames = [
    'January', 'February', 'March', 'April', 'May', 'June',
    'July', 'August', 'September', 'October', 'November', 'December'
  ];
  const monthName = monthNames[month - 1] || `Month ${month}`;
  const monthStr = String(month).padStart(2, '0');
  const filename = `TT-Monthly-Invoice-Report-${year}-${monthStr}.pdf`;

  let currentY = 16;

  // 1. Header Banner
  doc.setFillColor(24, 24, 27); // Dark Zinc #18181b
  doc.rect(0, 0, pageWidth, 32, 'F');

  // Title & Subtitle
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.setTextColor(234, 179, 8); // Amber gold #eab308
  doc.text('THENNAKOON TOURS (PVT) LTD', marginX, currentY);

  doc.setFontSize(11);
  doc.setTextColor(255, 255, 255);
  doc.text(`Monthly Invoice Report — ${monthName} ${year}`, marginX, currentY + 7);

  // Top Right Generated Date & By
  const genDateStr = new Date().toLocaleDateString('en-GB', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
  });
  const genUser = profile?.full_name ? `${profile.full_name} (${profile.role || 'Staff'})` : 'System';

  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(180, 180, 180);
  doc.text(`Generated Date: ${genDateStr}`, pageWidth - marginX, currentY, { align: 'right' });
  doc.text(`Generated By: ${genUser}`, pageWidth - marginX, currentY + 5, { align: 'right' });

  currentY = 38;

  // 2. Compute Financial Totals (Excluding Cancelled and Archived)
  const validInvoices = invoices.filter((i) => i.status !== 'Cancelled');
  const totalValue = validInvoices.reduce((sum, i) => sum + (i.net_amount || 0), 0);
  const advancePayments = validInvoices.reduce((sum, i) => sum + (i.advance_payment || 0), 0);
  const totalCollected = advancePayments + monthlyPaymentsCollected;
  const totalOutstanding = validInvoices.reduce((sum, i) => sum + (i.balance_due || 0), 0);
  const collectionRate = totalValue > 0 ? (totalCollected / totalValue) * 100 : 0;

  // Status Counts
  const draftCount = invoices.filter((i) => i.status === 'Draft').length;
  const issuedCount = invoices.filter((i) => i.status === 'Issued').length;
  const paidCount = invoices.filter((i) => i.status === 'Paid').length;
  const partialCount = invoices.filter((i) => i.status === 'Partially Paid').length;
  const overdueCount = invoices.filter((i) => i.status === 'Overdue').length;
  const cancelledCount = invoices.filter((i) => i.status === 'Cancelled').length;

  // Financial Summary Cards Box (5 Columns)
  doc.setFillColor(245, 245, 247);
  doc.setDrawColor(220, 220, 225);
  doc.roundedRect(marginX, currentY, contentWidth, 22, 2, 2, 'FD');

  const cardW = contentWidth / 5;
  const drawSummaryCell = (title: string, val: string, x: number, isHighlight = false) => {
    doc.setFontSize(7);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(100, 100, 100);
    doc.text(title.toUpperCase(), x + cardW / 2, currentY + 6, { align: 'center' });

    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    if (isHighlight) {
      doc.setTextColor(180, 120, 0); // Amber
    } else {
      doc.setTextColor(20, 20, 20);
    }
    doc.text(val, x + cardW / 2, currentY + 14, { align: 'center' });
  };

  drawSummaryCell('Total Value', formatLKR(totalValue), marginX);
  drawSummaryCell('Month Payments', formatLKR(monthlyPaymentsCollected), marginX + cardW);
  drawSummaryCell('Advances', formatLKR(advancePayments), marginX + cardW * 2);
  drawSummaryCell('Balance Due', formatLKR(totalOutstanding), marginX + cardW * 3, true);
  drawSummaryCell('Collection Rate', `${collectionRate.toFixed(1)}%`, marginX + cardW * 4);

  currentY += 26;

  // Status Counts Bar
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(80, 80, 80);
  const statusStr = `Statuses: Paid (${paidCount}) | Partially Paid (${partialCount}) | Issued (${issuedCount}) | Draft (${draftCount}) | Overdue (${overdueCount}) | Cancelled (${cancelledCount})`;
  doc.text(statusStr, marginX, currentY);

  currentY += 5;

  // 3. Invoice Items AutoTable
  const tableData = invoices.map((inv) => [
    inv.invoice_number,
    formatDate(inv.invoice_date),
    inv.customer_name || 'N/A',
    inv.customer_phone || '-',
    inv.vehicle_name || inv.vehicle_registration_number || '-',
    formatLKR(inv.net_amount || 0),
    formatLKR(inv.amount_paid || 0),
    formatLKR(inv.balance_due || 0),
    inv.status,
  ]);

  autoTable(doc, {
    startY: currentY,
    head: [
      [
        'Invoice No',
        'Date',
        'Customer',
        'Phone',
        'Vehicle',
        'Net Amount',
        'Amount Paid',
        'Balance Due',
        'Status',
      ],
    ],
    body: tableData,
    margin: { left: marginX, right: marginX, top: 15, bottom: 15 },
    theme: 'grid',
    headStyles: {
      fillColor: [24, 24, 27],
      textColor: [234, 179, 8],
      fontSize: 8,
      fontStyle: 'bold',
      halign: 'left',
    },
    bodyStyles: {
      fontSize: 7.5,
      textColor: [40, 40, 40],
      cellPadding: 2.2,
    },
    columnStyles: {
      0: { fontStyle: 'bold', cellWidth: 24 },
      1: { cellWidth: 20 },
      2: { cellWidth: 28 },
      3: { cellWidth: 22 },
      4: { cellWidth: 22 },
      5: { halign: 'right', cellWidth: 22 },
      6: { halign: 'right', cellWidth: 22 },
      7: { halign: 'right', cellWidth: 22 },
      8: { halign: 'center', cellWidth: 20, fontStyle: 'bold' },
    },
    didParseCell: (data) => {
      // Highlight Cancelled rows in light red background
      if (data.section === 'body' && data.row.cells[8]?.text[0] === 'Cancelled') {
        data.cell.styles.fillColor = [254, 242, 242];
        data.cell.styles.textColor = [185, 28, 28];
      }
    },
    didDrawPage: (data) => {
      // Page Number Footer
      const totalPages = (doc as unknown as { internal: { getNumberOfPages: () => number } }).internal.getNumberOfPages();
      const currentPage = data.pageNumber;
      doc.setFontSize(7.5);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(120, 120, 120);
      doc.text(
        `Page ${currentPage} of ${totalPages}`,
        pageWidth - marginX,
        pageHeight - 8,
        { align: 'right' }
      );
      doc.text(
        'Thennakoon Tours (Pvt) Ltd — Confidential Monthly Invoice Report',
        marginX,
        pageHeight - 8
      );
    },
  });

  // Save PDF file download
  doc.save(filename);
}
