import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Invoice, InvoicePayment, Profile } from '@/lib/types';
import { formatDate, formatLKR } from '@/lib/utils';

export interface CustomerStatementItem {
  date: string;
  type: 'Invoice' | 'Payment';
  reference: string;
  description: string;
  invoicedAmount: number;
  paidAmount: number;
  balance: number;
}

export function generateCustomerStatementPdf(
  customerName: string,
  customerInvoices: Invoice[],
  customerPayments: InvoicePayment[],
  profile?: Profile | null
): void {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = 210;
  const pageHeight = 297;
  const marginX = 14;
  const contentWidth = pageWidth - marginX * 2; // 182mm

  const filename = `TT-Statement-${customerName.replace(/[^a-zA-Z0-9]/g, '-')}-${new Date().toISOString().split('T')[0]}.pdf`;

  let currentY = 16;

  // 1. Dark Header Banner
  doc.setFillColor(24, 24, 27); // #18181b
  doc.rect(0, 0, pageWidth, 34, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.setTextColor(234, 179, 8); // #eab308
  doc.text('THENNAKOON TOURS (PVT) LTD', marginX, currentY);

  doc.setFontSize(11);
  doc.setTextColor(255, 255, 255);
  doc.text('CUSTOMER STATEMENT OF ACCOUNT', marginX, currentY + 7);

  const genDateStr = new Date().toLocaleDateString('en-GB', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
  });
  const genUser = profile?.full_name ? `${profile.full_name} (${profile.role || 'Staff'})` : 'System';

  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(180, 180, 180);
  doc.text(`Statement Date: ${genDateStr}`, pageWidth - marginX, currentY, { align: 'right' });
  doc.text(`Generated By: ${genUser}`, pageWidth - marginX, currentY + 5, { align: 'right' });

  currentY = 40;

  // 2. Customer Info Header Box
  const firstInv = customerInvoices[0];
  const phone = firstInv?.customer_phone || '-';
  const email = firstInv?.customer_email || '-';
  const address = firstInv?.customer_address || '-';

  doc.setFillColor(248, 248, 250);
  doc.setDrawColor(220, 220, 225);
  doc.roundedRect(marginX, currentY, contentWidth, 24, 2, 2, 'FD');

  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(120, 120, 120);
  doc.text('ACCOUNT HOLDER DETAILS', marginX + 4, currentY + 6);

  doc.setFontSize(11);
  doc.setTextColor(20, 20, 20);
  doc.text(customerName, marginX + 4, currentY + 13);

  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(80, 80, 80);
  doc.text(`Phone: ${phone}  |  Email: ${email}`, marginX + 4, currentY + 19);
  doc.text(`Address: ${address.slice(0, 60)}`, pageWidth - marginX - 4, currentY + 19, { align: 'right' });

  currentY += 28;

  // 3. Statement Financial Totals (Excluding Cancelled)
  const validInvoices = customerInvoices.filter((i) => i.status !== 'Cancelled');
  const totalInvoiced = validInvoices.reduce((sum, i) => sum + (i.net_amount || 0), 0);
  const activePayments = customerPayments.filter((p) => !p.is_reversed);
  const totalPaymentsCollected = activePayments.reduce((sum, p) => sum + (p.amount || 0), 0);
  const totalAdvances = validInvoices.reduce((sum, i) => sum + (i.advance_payment || 0), 0);
  const grandTotalCollected = totalPaymentsCollected + totalAdvances;
  const currentOutstanding = validInvoices.reduce((sum, i) => sum + (i.balance_due || 0), 0);

  doc.setFillColor(245, 245, 247);
  doc.setDrawColor(220, 220, 225);
  doc.roundedRect(marginX, currentY, contentWidth, 20, 2, 2, 'FD');

  const cardW = contentWidth / 4;
  const drawSummaryCell = (title: string, val: string, x: number, isHighlight = false) => {
    doc.setFontSize(7.5);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(100, 100, 100);
    doc.text(title.toUpperCase(), x + cardW / 2, currentY + 6, { align: 'center' });

    doc.setFontSize(9.5);
    doc.setFont('helvetica', 'bold');
    if (isHighlight) {
      doc.setTextColor(220, 38, 38); // Red
    } else {
      doc.setTextColor(20, 20, 20);
    }
    doc.text(val, x + cardW / 2, currentY + 14, { align: 'center' });
  };

  drawSummaryCell('Total Invoices', `${validInvoices.length}`, marginX);
  drawSummaryCell('Total Invoiced', formatLKR(totalInvoiced), marginX + cardW);
  drawSummaryCell('Total Paid', formatLKR(grandTotalCollected), marginX + cardW * 2);
  drawSummaryCell('Balance Due', formatLKR(currentOutstanding), marginX + cardW * 3, true);

  currentY += 25;

  // 4. Ledger Entries Construction
  const ledgerEntries: CustomerStatementItem[] = [];

  // Add Invoices
  validInvoices.forEach((inv) => {
    ledgerEntries.push({
      date: inv.invoice_date,
      type: 'Invoice',
      reference: inv.invoice_number,
      description: inv.vehicle_name || inv.nature_of_invoice || 'Rental Service',
      invoicedAmount: inv.net_amount || 0,
      paidAmount: 0,
      balance: 0,
    });

    if (inv.advance_payment && inv.advance_payment > 0) {
      ledgerEntries.push({
        date: inv.invoice_date,
        type: 'Payment',
        reference: `${inv.invoice_number} (Advance)`,
        description: 'Advance Deposit Received',
        invoicedAmount: 0,
        paidAmount: inv.advance_payment,
        balance: 0,
      });
    }
  });

  // Add Payments
  activePayments.forEach((pay) => {
    ledgerEntries.push({
      date: pay.payment_date,
      type: 'Payment',
      reference: pay.reference_number || `PAY-${pay.id.slice(0, 6)}`,
      description: `Payment via ${pay.payment_method}`,
      invoicedAmount: 0,
      paidAmount: pay.amount || 0,
      balance: 0,
    });
  });

  // Sort Chronologically
  ledgerEntries.sort((a, b) => new Date(a.date).getTime() - new Date(b.date).getTime());

  // Calculate Running Balance
  let runningBal = 0;
  const tableData = ledgerEntries.map((entry) => {
    runningBal += entry.invoicedAmount - entry.paidAmount;
    return [
      formatDate(entry.date),
      entry.type,
      entry.reference,
      entry.description,
      entry.invoicedAmount > 0 ? formatLKR(entry.invoicedAmount) : '-',
      entry.paidAmount > 0 ? formatLKR(entry.paidAmount) : '-',
      formatLKR(Math.max(0, runningBal)),
    ];
  });

  autoTable(doc, {
    startY: currentY,
    head: [['Date', 'Type', 'Reference', 'Description', 'Invoiced (LKR)', 'Paid (LKR)', 'Running Balance']],
    body: tableData,
    margin: { left: marginX, right: marginX, top: 15, bottom: 15 },
    theme: 'grid',
    headStyles: {
      fillColor: [24, 24, 27],
      textColor: [234, 179, 8],
      fontSize: 8,
      fontStyle: 'bold',
      halign: 'left',
    },
    bodyStyles: {
      fontSize: 7.5,
      textColor: [40, 40, 40],
      cellPadding: 2.2,
    },
    columnStyles: {
      0: { cellWidth: 20 },
      1: { cellWidth: 18, fontStyle: 'bold' },
      2: { cellWidth: 28, fontStyle: 'bold' },
      3: { cellWidth: 40 },
      4: { halign: 'right', cellWidth: 24 },
      5: { halign: 'right', cellWidth: 24 },
      6: { halign: 'right', cellWidth: 28, fontStyle: 'bold' },
    },
    didDrawPage: (data) => {
      const totalPages = (doc as unknown as { internal: { getNumberOfPages: () => number } }).internal.getNumberOfPages();
      const currentPage = data.pageNumber;
      doc.setFontSize(7.5);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(120, 120, 120);
      doc.text(`Page ${currentPage} of ${totalPages}`, pageWidth - marginX, pageHeight - 8, { align: 'right' });
      doc.text('Thennakoon Tours (Pvt) Ltd — Customer Account Statement', marginX, pageHeight - 8);
    },
  });

  doc.save(filename);
}
